require("setups.icons")
require("setups.themes")
require("setups.mason")
require("setups.roslyn")
require("lsp")
require("treesitter")
require("setups.cmp")
require("setups.snacks")
require("setups.ui")
require("setups.git")
require("setups.dap")
require("setups.java")
require("setups.csharp")
require("setups.conform")
require("setups.tools")
require("setups.misc")

vim.cmd.colorscheme("gruvbox-material")
